### ISSUE TITLE
Runtime problems

### ISSUE THREAD

**Issue by koma520** [Toefinder/Shapley-Algorithms-Federated-Learning-#1]
When I was running the code federatedMR_main.py, it appeared IndexError: tuple index out of range.

**Comment by koma520** [comment]
0%|          | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/xiaoma/Downloads/Federated-Learning-PyTorch-master/src/federatedMR_main.py", line 122, in <module>
    model=copy.deepcopy(global_model), global_round=epoch)
  File "/Users/xiaoma/Downloads/Federated-Learning-PyTorch-master/src/update.py", line 69, in update_weights
    for batch_idx, (images, labels) in enumerate(self.trainloader):
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/xiaoma/Downloads/Federated-Learning-PyTorch-master/src/update.py", line 22, in __getitem__
    image, label = self.dataset[self.idxs[item]]
IndexError: tuple index out of range

 | Global Training Round : 1 |


I don't konw how to fix this. 
please help me with this problem.
Thanks!

**Comment by Toefinder** [comment]
> When I was running the code federatedMR_main.py, it appeared IndexError: tuple index out of range.

Can you send me a list of actual commands you have run? (hide any sensitive info if you have) And have you performed the data processing similar to what is done in the jupyter notebooks?

**Comment by koma520** [comment]
> > When I was running the code federatedMR_main.py, it appeared IndexError: tuple index out of range.
> 
> Can you send me a list of actual commands you have run? (hide any sensitive info if you have) And have you performed the data processing similar to what is done in the jupyter notebooks?



I have run this command"python federatedMR_main.py --model=mlp --dataset=MNIST --num_users=10 --traindivision=1 --epochs=10"
I haven’t  performed the data processing similar to what is done in the jupyter notebooks, I just use the Mnist Dataset from the website.
The data set structure is shown  in here.
MNIST
          processed
                            test.pt training.pt
          raw
                 t10k-images-idx3-ubyte  t10k-labels-idx1-ubyte  train-images-idx3-ubyte  train-labels-idx1-ubyte

**Comment by Toefinder** [comment]
Please refer to the [`get_dataset()`](https://github.com/Toefinder/Shapley-Algorithms-Federated-Learning-/blob/5bb086a5bb6065066dd84c1f839dd1c4700cec54/src/utils.py#L35) function to understand the folder structure to load data. And you need to perform the data processing, to get them into the different "train division", aka different experiment settings (refer to the data processing portion in the pdf report).

The folder structure looks something like this

```markdown
data
  |- OurMNIST
    |- dictionary1.out
    |- dictionary2.out
```

**Comment by koma520** [comment]
Thank u! I can run successfully by processing the mnist data set.

**Comment by koma520** [comment]
I have run this command ----- python federatedMR_main.py --model=mlp --dataset=MNIST --num_users=10 --traindivision=1 --epochs=10There was an error as shown in the picture above.I haven’t  performed the data processing similar to what is done in the jupyter notebooks, I just use the Mnist Dataset from the website.The data set structure is shown in the figure below.2021年9月17日 下午4:47，Quang Anh ***@***.***> 写道：
When I was running the code federatedMR_main.py, it appeared IndexError: tuple index out of range.
Can you send me a list of actual commands you have run? (hide any sensitive info if you have) And have you performed the data processing similar to what is done in the jupyter notebooks?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
